### ISSUE TITLE
do I need a .readthedocs.yml file?

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/nbQA#69]

**Comment by s-weigand** [comment]
You don't necessarily need it since you can adjust most settings in the RTD project admin web interface.
But it is a great way to unify the settings across projects with the same structure (i.e. if you use [coockiecutter](https://github.com/cookiecutter/cookiecutter) to setup projects)

**Comment by MarcoGorelli** [comment]
Thanks @s-weigand ! Yeah I've been managing fine with the web interface, think I'll stick to that for the moment (but if it's something you have experience with and fancied submitting a PR, that'd be much appreciated!)
