### ISSUE TITLE
Currently doesn't handle line magic in notebooks when using black --check

### ISSUE THREAD

**Issue by HD23me** [MarcoGorelli/nbQA#97]
For example the line 

`% matplotlib inline`

results in the error message 

```
Cannot parse: x:x: %matplotlib inline
oh no!
```

running on - Windows 10 10.0.17134

**Comment by MarcoGorelli** [comment]
massive thanks for the report @HD23me !

**Comment by MarcoGorelli** [comment]
If you upgrade to the latest version, I'd like to think it's fixed
```
pip install -U nbqa
```

**Comment by MarcoGorelli** [comment]
@all-contributors please add @HD23me bug
